// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQm3DBDBOcoSp0wkV_ReUzSv_UREnIn2k',
    appId: '1:669022636133:web:e8cc4cb9c6a6ea32c9de8c',
    messagingSenderId: '669022636133',
    projectId: 'drop-note-f5e07',
    authDomain: 'drop-note-f5e07.firebaseapp.com',
    storageBucket: 'drop-note-f5e07.firebasestorage.app',
    measurementId: 'G-THT9GHWQMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1dhgNDpeUs8fLkBDPy-l4YedrdN_lvU',
    appId: '1:669022636133:android:d255d4f8d1ab0e06c9de8c',
    messagingSenderId: '669022636133',
    projectId: 'drop-note-f5e07',
    storageBucket: 'drop-note-f5e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwX-73oI1HiCoFsNtkuZoIhsy8XX3pp8I',
    appId: '1:669022636133:ios:7846a141c347b211c9de8c',
    messagingSenderId: '669022636133',
    projectId: 'drop-note-f5e07',
    storageBucket: 'drop-note-f5e07.firebasestorage.app',
    iosBundleId: 'com.example.dropNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwX-73oI1HiCoFsNtkuZoIhsy8XX3pp8I',
    appId: '1:669022636133:ios:7846a141c347b211c9de8c',
    messagingSenderId: '669022636133',
    projectId: 'drop-note-f5e07',
    storageBucket: 'drop-note-f5e07.firebasestorage.app',
    iosBundleId: 'com.example.dropNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQm3DBDBOcoSp0wkV_ReUzSv_UREnIn2k',
    appId: '1:669022636133:web:f3ce3c6622099545c9de8c',
    messagingSenderId: '669022636133',
    projectId: 'drop-note-f5e07',
    authDomain: 'drop-note-f5e07.firebaseapp.com',
    storageBucket: 'drop-note-f5e07.firebasestorage.app',
    measurementId: 'G-NV8CKV268N',
  );
}
