// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxHuSwylYgo5rK8D7VR3Py_4VvNkIPEM',
    appId: '1:880863204158:web:72df652087b8d986c2126f',
    messagingSenderId: '880863204158',
    projectId: 'qrventory-b0ea6',
    authDomain: 'qrventory-b0ea6.firebaseapp.com',
    storageBucket: 'qrventory-b0ea6.firebasestorage.app',
    measurementId: 'G-4F9YTTWZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9DUMeZ7D2ii9Be40ITSLLYHjqNBZsfs',
    appId: '1:880863204158:android:4fdf51c9e0bbdbf0c2126f',
    messagingSenderId: '880863204158',
    projectId: 'qrventory-b0ea6',
    storageBucket: 'qrventory-b0ea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLxGGSQ9IiH8kHThm3RYRpW0QavOm2g0',
    appId: '1:880863204158:ios:a8638f2928519463c2126f',
    messagingSenderId: '880863204158',
    projectId: 'qrventory-b0ea6',
    storageBucket: 'qrventory-b0ea6.firebasestorage.app',
    iosClientId: '880863204158-tv7rvm8v6l300suvfoga2m5nl251d9l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrventoryUpdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLxGGSQ9IiH8kHThm3RYRpW0QavOm2g0',
    appId: '1:880863204158:ios:a8638f2928519463c2126f',
    messagingSenderId: '880863204158',
    projectId: 'qrventory-b0ea6',
    storageBucket: 'qrventory-b0ea6.firebasestorage.app',
    iosClientId: '880863204158-tv7rvm8v6l300suvfoga2m5nl251d9l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrventoryUpdated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxHuSwylYgo5rK8D7VR3Py_4VvNkIPEM',
    appId: '1:880863204158:web:91f89301d930b4aac2126f',
    messagingSenderId: '880863204158',
    projectId: 'qrventory-b0ea6',
    authDomain: 'qrventory-b0ea6.firebaseapp.com',
    storageBucket: 'qrventory-b0ea6.firebasestorage.app',
    measurementId: 'G-7PG032V8TQ',
  );

}